export enum ErrorCode
{
	UNKNOWN				= 'ERR:UNKNOWN',
	EMPTY_VALUE			= 'ERR:EMPTYVALUE',
	INVALID_SIGN		= 'ERR:INVALIDSIGN',
	NO_SIGN				= 'ERR:NOSIGN',
	NO_PRIVATEKEY		= 'ERR:NOPRIVATEKEY',
	NO_PUBLICKEY		= 'ERR:NOPUBLICKEY',
}